### ISSUE TITLE
Support submodule caching

### ISSUE THREAD

**Issue by sya-ri** [ComunidadAylas/PackSquash-action#25]
### Bug description

[git_set_file_times.ts](https://github.com/ComunidadAylas/PackSquash-action/blob/master/src/git_set_file_times.ts) will only run files in the root git repository, ignoring files in submodules.

### Reproduction steps

Use a submodule as the pack directory.

### Expected behavior

Use caches.

### Attached files or repository

https://github.com/sya-ri/PackSquash-action-test

### Additional context

I've talked about it before, but I created this issue for TODO.

> ```shell
> git config --file .gitmodules --get-regexp path | awk '{ print $2 }'
> ```
> https://stackoverflow.com/questions/12641469/list-submodules-in-a-git-repository

**Comment by AlexTMjugador** [comment]
Thank you. Do you happen to know if the issue happened in v2 too, when a Perl script was used to set the file modification times?

**Comment by sya-ri** [comment]
Yes, [sya-ri/PackSquash-action-test](https://github.com/sya-ri/PackSquash-action-test) runs master, v2, and v3, but none of them use the cache.

**Comment by sya-ri** [comment]
I'm currently working on this: https://github.com/sya-ri/PackSquash-action/tree/support-submodule-caching

**Comment by AlexTMjugador** [comment]
PR #51 was just merged, implementing submodule caching support, so this issue is resolved.
