### ISSUE TITLE
ARM action support

### ISSUE THREAD

**Issue by xMikux** [ComunidadAylas/PackSquash-action#4]
Not a bug, but if you run on selfhost runner, and using arm cpu, than you will get this error
![image](https://user-images.githubusercontent.com/26039249/135480106-b523515e-c7fd-488c-8322-d5eb8b72c259.png)
because default, action will download x64 version of packsquash, it will be great if this action can work on arm system!

**Comment by AlexTMjugador** [comment]
This is an oversight, as we didn't think about the possibility of this action being executed under a GitHub Actions runner in an architecture other than x64. And PackSquash already supports the ARM64 architecture, so there is no real reason for the action to not bother checking on what architecture it is running on to download the proper executable.

This check can be easily done via the `uname -m` command, which is [defined by POSIX](https://pubs.opengroup.org/onlinepubs/009604599/utilities/uname.html) to return the system "hardware type". Linux implementation of the underlying syscalls indeed returns the architecture codename, which is `aarch64` for the supported PackSquash ARM64 port, and `x86_64` for x64.

Thanks for reporting this issue!
