### ISSUE TITLE
Iron out submodule caching support

### ISSUE THREAD

**Issue by AlexTMjugador** [ComunidadAylas/PackSquash-action#54]
### Related problem

PR #51 introduced submodule caching support, which greatly sped up workflow execution times. However, while doing https://github.com/sya-ri/PackSquash-action-test/pull/1 I've stumbled upon an unhandled exception related to the changes introduced in that PR.

That particular problem was fixed, but this fact and the lack of thorough testing of that PR suggest that there might be some relevant issues left.

### Proposed solution

Submodule caching support should be thoroughly tested and reviewed before the next action version is released. Maybe my fix was enough to iron things out, but I didn't test complex scenarios such as nested submodules.

### Alternative solutions

- **Do nothing**. This is a risky proposition that I'd rather avoid.
- **Revert the PR**. This would be sad, because it contains useful changes, and I would not like to do that. However, it would guarantee that no new failures are introduced due to submodule caching.

### Additional context

@sya-ri was the original author of the PR and stated that the action "may need some changes" in response, but his unavailability and lack of commitment to look into the matter over the past months warrant this task to be written down and another pair of eyes to look at the problem.

**Comment by sya-ri** [comment]
I think that it throws an exception if it contains uncommitted files. I think there are other causes, but we need more research.

**Comment by AlexTMjugador** [comment]
Okay.

>[...] warrant [...] another pair of eyes to look at the problem.

Do you think it still is warranted? In other words, will I have to take care of this at some point?

**Comment by AlexTMjugador** [comment]
This is not really related to the issue at hand, but while ironing out stuff I've fixed problem matchers being broken by default since the action uses PackSquash with colored output: https://github.com/ComunidadAylas/PackSquash-action/commit/11fa3f7b230566c6f0dd2daad9a39964e5398605

**Comment by AlexTMjugador** [comment]
Good riddance to probably most of the caching issues that were left! :tada: 

Addressed by #55.
