### ISSUE TITLE
Generalize and publish the internal Docker container

### ISSUE THREAD

**Issue by AlexTMjugador** [ComunidadAylas/PackSquash-action#7]
The action internally uses a Docker container to set up a well-known Debian environment with GStreamer and Node.js packages, as recommended by the GitHub Actions documentation, because an action can't rely on such environment details (for example, it might be executed on a GitHub-provided Windows or macOS runner, where `apt` wouldn't even be available). This container reads environment variables configured by the GitHub runner (`GITHUB_WORKSPACE`, etc.), and expects a specific folder layout.

To achieve a better separation of concerns between the action and the Docker container itself, it'd be nice for the Docker container to not be tightly coupled with how the GitHub runner sets it up. The ultimate goal would be to publish the GitHub runner agnostic Docker container on Docker Hub, and make the action consume it (i.e. just be a nice frontend for that Docker image). I think it's possible to keep its files in this repository, though, and use some workflow to do the publishing. This separation has some benefits:

- [Separation of concerns](https://en.wikipedia.org/wiki/Separation_of_concerns) is a software design principle that leads to better software, as explained in the linked Wikipedia article.
- It would solve https://github.com/ComunidadAylas/PackSquash/issues/10, and help with https://github.com/ComunidadAylas/PackSquash/issues/38.
- It would allow to emulate a "poor man's" PackSquash Action of sorts in CI pipelines outside of GitHub, as long as they can run Docker containers easily, such as in GitLab.
- Because the Docker image is built and uploaded once to the Hub, each execution of the action won't have to build the image, which saves quite a bit of time. That's important in smaller packs, where the Docker image build takes longer than actually optimizing the pack.

**Comment by AlexTMjugador** [comment]
Node is needed for GitHub Actions specific features, such as uploading artifacts, because GitHub's JavaScript [Actions Toolkit](https://github.com/actions/toolkit) is meant to be ran on Node:

https://github.com/ComunidadAylas/PackSquash-action/blob/716a3fece60dfff03fc97fb1a0e5734be71420d4/entrypoint.sh#L390-L405

In https://github.com/ComunidadAylas/PackSquash-action/issues/2 I've discussed other ways of implementing these features, but overall Node was the sanest option. The approach of re-implementing the Toolkit in another environment, while technically possible, was not chosen because upon closer inspection it turned out that the Toolkit does some not documented anywhere optimizations that look prone to change over time, such as using the Azure storage SDK for URLs that match a certain hardcoded pattern, and it'd be a substantial maintenance effort to track and replicate these kind of breaking changes. It looks like when you develop a web application and have the Node "hammer" at your disposal, everything starts looking like a JavaScript "nail" :sweat_smile: 

GitHub Actions specific features aside, Node is not needed at all for PackSquash to work on a container, and can be removed. The image can be based on any sane Linux environment with a recent glibc and GStreamer, including slim Debian Bullseye (in fact, PackSquash builds are done on Debian Bullseye containers).

I think that your idea of generating two separate Docker images, one without GitHub-specific flair and another one with all that flair, is nice. Ideally, the GitHub-specific image should be based on the lightweight image, with a `FROM` instruction in its Dockerfile or something like that. I think that both images should be published, although in the case of the GitHub Actions image I'd only do so to avoid the time cost of having to build the image from scratch on each workflow, not for end-users to download.

In any case, it'd be nice to be able to use containers with different PackSquash versions. On the slim images, tags can help with that (although the functionality of `latest` would require building a new image with each PackSquash commit, and maybe GitHub Packages doesn't take it too kindly to have lots of tags for a single image for free; I haven't looked into this, though). However, I don't clearly see how the GitHub Actions image could be based on different slim images depending on the action parameters. Maybe there is a way I don't know of conditionally adding layers, or maybe just all the possible PackSquash versions can be added.

All of these can be interesting problems to solve, and if you want to contribute Dockerfiles that expose the internal action container in a more generic and useful way, it'd be appreciated :heart:

**Comment by realkarmakun** [comment]
Okay I think I figured it out. We would need to make two PackSquash Docker images, one would be based on slim and have just binary in it. The other one would be in this repo and  will make use of first one through multi-stage build and pull PackSquash binary to the node image. As I said before I think a better place for PackSquash Docker file would be in PackSquash original repo. The only concern I have right now is apt dependencies. Maybe there is a way to pull them along with PackSquash binary... I need to do some research and play around with it. As for `latest` tag I have some experience setting up https://github.com/marketplace/actions/push-to-ghcr so by default action behavior latest tag would be latest release so it's a breeze. If you okay with PackSquash repo having Dockerfile of it's own I'll fork and will try playing around with it

**Comment by realkarmakun** [comment]
Okay now I have some questions. How do you deploy PackSquash releases? Do you build them yourself?

**Comment by AlexTMjugador** [comment]
> The only concern I have right now is apt dependencies. Maybe there is a way to pull them along with PackSquash binary... I need to do some research and play around with it.

Each [build workflow execution](https://github.com/ComunidadAylas/PackSquash/actions/runs/1831679238) generates a `.deb` package artifact you can install with `apt install ./package.deb`. You might find that useful.

> If you okay with PackSquash repo having Dockerfile of it's own I'll fork and will try playing around with it.

Your arguments for putting the Dockerfile in the main PackSquash repository are reasonable. I haven't decided yet where I'd want that Dockerfile to live, but you can play around with it in the main repository. Moving it around if necessary sounds like an easy thing to do :smile: 

> How do you deploy PackSquash releases? Do you build them yourself? If so, do I need to setup Dockerfile that builds PackSquash from source? Or should I just download binary from apt repo?

To make a release I publish a GitHub Release manually after writing the release notes, let the build workflow run for the release publish event, and then attach its artifacts to the release. I try to do this shortly after the latest commit was pushed to minimize the chance that the build fails for some reason. I never build myself any artifact that I distribute to the public for several technical reasons. So you don't need to build PackSquash from source.

> Or should I just download binary from apt repo?

That would work for v0.3.0, but the APT repository only contains that release for now, and it will only contain stable releases. Unstable builds generated for each commit are not published to that repository, and versions released before the APT repository was introduced (v0.2.1 and older) can only be downloaded from GitHub Releases.

**Comment by realkarmakun** [comment]
> Each [build workflow execution](https://github.com/ComunidadAylas/PackSquash/actions/runs/1831679238) generates a .deb package artifact you can install with apt install ./package.deb. You might find that useful.

Sounds good, I'll think I can figure out how to pull it

**Comment by AlexTMjugador** [comment]
I've updated the PackSquash build workflows to also generate AppImages too: https://github.com/ComunidadAylas/PackSquash/actions/runs/1950773686

PackSquash AppImages may be interesting for this issue because they bundle their own copy of every required library, including glibc. Every executable and library within the AppImage is instructed to use those copies, and not the system libraries.

In theory, this allows to run PackSquash on containers based on musl images, such as Alpine, by extracting those AppImages to the image during the build process. I've not tested this yet, but I've tested running an AppImage built on Debian unstable on Debian Buster, and everything worked flawlessly.

**Comment by AlexTMjugador** [comment]
I've just tested running the extracted AppImage in an Alpine chroot and it worked fine!! :tada: :tada:

There's a ray of light for using Alpine-based containers with current PackSquash versions, finally!

**Comment by realkarmakun** [comment]
I am very much sorry for not updating you on this. At first I was busy with my other tasks, but now I'm busy with everything happening in the world and now can't finish what I started. Glad Alpine worked though! 🎉

**Comment by AlexTMjugador** [comment]
Don't worry, life is important too. Let me know if you make some progress on this! :heart:

**Comment by AlexTMjugador** [comment]
https://github.com/ComunidadAylas/PackSquash-action/pull/17 would supersede this improvement, but the Docker image generation knowledge we've gathered so far may be useful for other improvements.

**Comment by realkarmakun** [comment]
@AlexTMjugador Hey it's me. After a while I came back to this and now I think it doesn't really worth all the trouble trying to figure out alpine image (at least at the time). PackSquash with alpine using AppImage made 175mb image, which is a lot for "alpine with binary" kind of image. So I went with bullseye-slim and AppImage and it was 198mb. . At least to my taste trying to get this 20mb down doesn't really worth the time. Also don't really believe it would be all that beneficial to use apt package. And using apt would require additional RUN instruction in Dockerfile, which would create another fs layer and get image size up.

To sum it up: using Alpine is **not** really beneficial in this case AFAIK.
I made a "playground" fork to test Actions out as well as ghcr.io: it's here https://github.com/realkarmakun/PackSquash
Though it's absolute chaos of a PR, so I'll made another clean one. But you can look at the example package page here: https://github.com/users/realkarmakun/packages/container/package/packsquash. Image is available at ghcr.io/realkarmakun/packsquash:latest

In it's current state image can be utilized, just need to supply `--appimage-extract-and-run`. Which is a matter of discussion as well, we maybe can provide FUSE for it to work without this flag, since it won't take much space relative to whole image size. As of writing this I yet need to test it.

Just to showcase example of using generic docker image, I want to show Gitlab CI/CD job example utilizing PackSquash image:
```yaml
build-job:
  stage: build
  image: 
    name: ghcr.io/realkarmakun/packsquash:latest
    entrypoint: [""]
  script:
    - packsquash --appimage-extract-and-run packsquash-config.toml
  artifacts:
    paths:
      - rustme-rp.zip
```
kaniko docker image builder uses the same way of organizing entrypoint image, so I consider this example using best practices :)

**Comment by AlexTMjugador** [comment]
Thank you a lot for looking into this, @realkarmakun! :heart: It's great to know how a slim Debian based image fares in comparison with an Alpine-based one, and I appreciate the detailed description of your findings.

As you saw, AppImages require FUSE to run, but FUSE can't be used properly in Docker containers, so you need to extract the image files and run them. There are no workarounds I know for that, but it isn't a showstopper.

The trouble with Alpine stems from the fact that the AppImage runtime is linked against an old glibc version, but Alpine has no glibc at all, so in that case even extracting the image doesn't work, because the runtime can't start. There are workarounds that are not so difficult to implement after you know them, such as extracting the AppImage in the build host and then copying that to the container filesystem, but I understand that the most bloat here is coming from GStreamer and wasting ~20 MiB due to a different distro choice is not that relevant.

**Comment by realkarmakun** [comment]
I was almost able to get it up and running on Alpine with https://github.com/sgerrand/alpine-pkg-glibc but in the end got
```
gnu_dev_makedev: symbol not found
```
I wasn't able to figure out what exact issue is, so decided to try slim image.
Also here is PR: https://github.com/ComunidadAylas/PackSquash/pull/111 :)
As mentioned there you as owner need to add token with `write:package` permission as secret with name REGISTRY_TOKEN

**Comment by AlexTMjugador** [comment]
https://github.com/ComunidadAylas/PackSquash/pull/111 supersedes this issue for all intents and purposes, so I'm closing it!
