### ISSUE TITLE
Vorbis error: Library error: vorbisfile error calling ov_open_callbacks: OV_ENOTVORBIS

### ISSUE THREAD

**Issue by SrBedrock** [ComunidadAylas/PackSquash-action#84]
### Bug description

assets/minecraft/sounds/welcome.ogg: Vorbis error: Library error: vorbisfile error calling ov_open_callbacks: OV_ENOTVORBIS: not Vorbis data

### Reproduction steps

try to compress a .ogg file

### Expected behavior

no errors

**Comment by AlexTMjugador** [comment]
Hi, thanks for reporting the issue. Have you double checked that the `assets/minecraft/sounds/welcome.ogg` file on your pack is truly an audio file in the Ogg Vorbis format? PackSquash only supports those, as Minecraft: Java Edition does. You can check by using external tools like [this](https://www.checkfiletype.com/).
